// Generated by https://quicktype.io

export interface TransactionResponse {
  id: string;
  bookingId: string;
  transactionName: string;
  transactionMethod: string;
  transactionDate: Date;
  transactionAmount: number;
  transactionStatus: string;
  bankCode: string;
  reason: string;
  transactionType: string;
}

export interface TransactionParams extends RootRequest {}
