import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import ReactQueryProvider from "@/components/query-client-provider";
import { Layout } from "@/components/homepage/layout-home";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      
          <Layout>{children}</Layout>
     
    </div>
  );
}
